apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rajbuggy
  template:
    metadata:
      labels:
        app: rajbuggy
    spec:
      containers:
      - name: rajbuggy
        image: 289355592657.dkr.ecr.us-west-2.amazonaws.com/raj:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rajbuggy
    k8s-app: rajbuggy
  name: rajbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: rajbuggy
